# Generated by Django 2.0.2 on 2018-06-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ima',
            new_name='Img',
        ),
    ]
